# NumPy Basics: Arrays and Vectorized Computation

In [1]:
import numpy as np

In [2]:
# Creating ndarrays
data1 = [6, 7.5, 8, 0, 1]

In [3]:
arr1 = np.array(data1)

In [4]:
arr1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [5]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [6]:
arr2 = np.array(data2)

In [7]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
arr2.ndim

2

In [9]:
arr2.shape

(2L, 4L)

In [10]:
arr1.dtype

dtype('float64')

In [11]:
arr2.dtype

dtype('int32')

In [12]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [15]:
np.zeros((3,6))

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [17]:
np.empty((2, 3, 2))

array([[[  2.68690685e-316,   2.68296618e-316],
        [  0.00000000e+000,   0.00000000e+000],
        [  0.00000000e+000,   0.00000000e+000]],

       [[  0.00000000e+000,   0.00000000e+000],
        [  0.00000000e+000,   0.00000000e+000],
        [  0.00000000e+000,   0.00000000e+000]]])

In [18]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [19]:
np.asarray(data1)

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [20]:
np.ones_like(arr1)

array([ 1.,  1.,  1.,  1.,  1.])

In [21]:
np.zeros_like(arr2)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [44]:
np.empty_like(np.ones((3,2)))

array([[  1.69176844e-052,   3.53853344e-057],
       [  8.24632423e+010,   1.48575701e-076],
       [  2.33732734e-316,   2.47032823e-323]])

In [26]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [27]:
np.identity(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [49]:
# Type casting
arr2.dtype

dtype('int32')

In [50]:
float_arr2 = arr2.astype(np.float64)

In [51]:
float_arr2

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.]])

In [52]:
arr3 = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [53]:
int_arr3 = arr3.astype(np.int32)

In [54]:
int_arr3

array([ 3, -1, -2,  0, 12, 10])

In [56]:
numeric_strings = np.array(['1.25', '-9.6', '42'])

In [57]:
numeric_strings.dtype

dtype('S4')

In [59]:
# NumPy is smart enough to alias the Python types to the equivalent dtypes.
numeric_strings.astype(float)

array([  1.25,  -9.6 ,  42.  ])

In [65]:
# You can also use another array’s dtype attribute:
int_array = np.arange(10)
string_array = np.array(['1', '2', '3'])

In [89]:
int2str_array = int_array.astype(string_array.dtype)
# astype always create a new array
int2str_array = np.append(int2str_array, [10])
print int2str_array
print int_array

['0' '1' '2' '3' '4' '5' '6' '7' '8' '9' '10']
[0 1 2 3 4 5 6 7 8 9]
